# Docs:
# https://aka.ms/yaml

trigger:
  - master
pool:
  name: Hosted Ubuntu 1604
steps:
- task: AzureResourceGroupDeployment@2
  displayName: "Deploy hmctssandbox"
  inputs:
    azureSubscription: 'azurerm-sandbox'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'cnp-acr-rg'
    location: 'UK South'
    deploymentMode: 'Incremental'
    templateLocation: 'Linked artifact'
    csmFile: 'template.json'
    overrideParameters: '-name hmctssandbox'
